In [1]:
import numpy as np

In [3]:
arr_2d =  np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
arr_2d[1][2

np.int64(30)

In [20]:
arr = np.arange(1,11)

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
bool_arr = arr >5

In [24]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [26]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [27]:
arr_2d = np.arange(50).reshape(5,10)

In [28]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
 arr_2d [1:3,3:5]

array([[13, 14],
       [23, 24]])

In [34]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])