In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.rand(5)

array([0.91172387, 0.10750653, 0.87376152, 0.445652  , 0.36110769])

In [32]:
np.random.rand(5,5)

array([[0.14950039, 0.42406663, 0.97587507, 0.54838538, 0.95877188],
       [0.77986407, 0.2552125 , 0.30416832, 0.88303587, 0.02815212],
       [0.01877485, 0.26718041, 0.07751574, 0.18160278, 0.08854935],
       [0.25277281, 0.91331244, 0.88641347, 0.17935151, 0.17981007],
       [0.05385034, 0.03812327, 0.21171661, 0.5185202 , 0.64457603]])

In [34]:
np.random.randn(4,4)

array([[ 0.91851094, -0.27136263, -0.05304072,  1.82425899],
       [ 1.76939102,  0.04970216, -0.44825564, -0.61611972],
       [-0.12511405,  1.0503302 , -0.02607697,  1.65249645],
       [ 0.83370503,  1.2533574 ,  0.04159987, -0.71746661]])

In [38]:
np.random.randint(1,100,10)

array([44, 98, 83, 19, 78, 43, 99, 19, 58, 41], dtype=int32)

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
ranarr

array([30, 22, 13, 39,  2, 47, 20, 47,  0, 21], dtype=int32)

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
 ranarr.max()

np.int32(47)

In [47]:
ranarr.min()

np.int32(0)

In [48]:
ranarr.argmax()

np.int64(5)

In [49]:
ranarr.argmin()

np.int64(8)

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

In [55]:
arr.dtype

dtype('int64')

In [56]:
from numpy.random import randint

In [57]:
randint(2,10)

4